### ISSUE TITLE
need help with github workflow deploy config

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/docs.serp.co#1]
Issues: https://github.com/serpcompany/docs.serp.co/actions

**Comment by francislabountyjr** [comment]
It's missing the env var `NUXT_UI_PRO_LICENSE`

**Comment by devinschumacher** [comment]
i know i tried adding that a few times using chat and claude and google but they just kept doing it wrong AND changing other shit in the fucking file 😭 @francislabountyjr

**Comment by devinschumacher** [comment]
Resolved by #2

**Comment by devinschumacher** [comment]
Duplicate to #2

**Comment by devinschumacher** [comment]
Duplicate to #2
